name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj

      - name: Restore
        run: dotnet restore BahmanM.Flow.sln

      - name: Build
        run: dotnet build BahmanM.Flow.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BahmanM.Flow.sln --configuration Release --no-build --verbosity normal

